os: Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

cache: c:\tools\vcpkg\installed\

install:
  - vcpkg install sqlite3:x64-windows

build_script:
  - cmake --version
  - cmake -B build -DCMAKE_CXX_FLAGS="/EHsc /wd4503" -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - cmake --build build --config %configuration%
  - cd build 
  - dir
  - cmake --build build --config %configuration% --target Test